#==========================================================================================
# ABOUT THIS MACRO
# Description: Description of simulation world and detector(s) geometry
# Author: Mateusz Bała
# E-mail: bala.mateusz@gmail.com
#==========================================================================================

/gate/geometry/setMaterialDatabase    GateMaterials.db

#==========================================================================================
# Simulation world description
# Below: simulation world as cube with a side length equal 300 cm
#==========================================================================================

/gate/world/geometry/setXLength 300. cm
/gate/world/geometry/setYLength 300. cm
/gate/world/geometry/setZLength 300. cm
#/gate/world/vis/setVisible 1 #To hide world's frame please set 0

#==========================================================================================
# Fantom geometry
#==========================================================================================

#/gate/world/daughters/name box_with_water
#/gate/world/daughters/systemType scanner
#/gate/world/daughters/insert box
#/gate/box_with_water/setMaterial Water
#/gate/box_with_water/geometry/setXLength 30 mm
#/gate/box_with_water/geometry/setYLength 30 mm
#/gate/box_with_water/geometry/setZLength 20 cm
#/gate/box_with_water/placement/setTranslation  0 0 0 mm
#/gate/box_with_water/vis/forceWireframe
#/gate/box_with_water/vis/setVisible 1

#==========================================================================================
# Detector geometry
# Below: Cylindrical detector (with name "detector") with inner radius equal 50 cm 
# and outer radius equal 52 cm. Heights of this detector is 60 cm.
#==========================================================================================
/gate/world/daughters/name detector1
/gate/world/daughters/systemType scanner
/gate/world/daughters/insert box
/gate/detector1/setMaterial Air
/gate/detector1/geometry/setXLength 19 mm
/gate/detector1/geometry/setYLength 7 mm
/gate/detector1/geometry/setZLength 52 cm
/gate/detector1/placement/setTranslation  425 0 0 mm
#/gate/detector1/vis/forceWireframe
#/gate/detector1/vis/setVisible 0

# C R Y S T A L

/gate/detector1/daughters/name crystal1
/gate/detector1/daughters/insert box
/gate/crystal1/placement/setTranslation 0 0 0 cm
/gate/crystal1/geometry/setXLength 19   mm
/gate/crystal1/geometry/setYLength 7   mm
/gate/crystal1/geometry/setZLength 50    cm
/gate/crystal1/setMaterial EJ230
#/gate/crystal1/vis/forceSolid
#/gate/crystal1/vis/setColor white
#/gate/crystal1/vis/setVisible 1

#proverit' chto eto
#
# R E P E A T E R S

/gate/detector1/repeaters/insert ring
/gate/detector1/ring/setRepeatNumber 48

# A T T A C H M E N T S

/gate/systems/detector1/level1/attach crystal1  
#/gate/crystal1/attachCrystalSD 

############ 2nd LAYER ############ 

# S Y S T E M

/gate/world/daughters/name detector2
/gate/world/daughters/systemType scanner
/gate/world/daughters/insert box
/gate/detector2/setMaterial Air
/gate/detector2/geometry/setXLength 19 mm
/gate/detector2/geometry/setYLength 7 mm
/gate/detector2/geometry/setZLength 52 cm
/gate/detector2/placement/setTranslation  467.5 0 0 mm
#/gate/detector2/vis/forceWireframe
#/gate/detector2/vis/setVisible 0

# C R Y S T A L

/gate/detector2/daughters/name crystal2
/gate/detector2/daughters/insert box
/gate/crystal2/placement/setTranslation 0 0 0 cm
/gate/crystal2/geometry/setXLength 19   mm
/gate/crystal2/geometry/setYLength 7   mm
/gate/crystal2/geometry/setZLength 50    cm
/gate/crystal2/setMaterial EJ230
#/gate/crystal2/vis/forceSolid
#/gate/crystal2/vis/setColor white
#/gate/crystal2/vis/setVisible 1

# R E P E A T E R S

/gate/detector2/repeaters/insert ring
/gate/detector2/ring/setFirstAngle 3.9130434782608696 deg
/gate/detector2/ring/setRepeatNumber 48

# A T T A C H M E N T S

/gate/systems/detector2/level1/attach crystal2  
#/gate/crystal2/attachCrystalSD 

############ 3rd LAYER ############ 

# S Y S T E M

/gate/world/daughters/name detector3
/gate/world/daughters/systemType scanner
/gate/world/daughters/insert box
/gate/detector3/setMaterial Air
/gate/detector3/geometry/setXLength 19 mm
/gate/detector3/geometry/setYLength 7 mm
/gate/detector3/geometry/setZLength 52 cm
/gate/detector3/placement/setTranslation  575 0 0 mm
#/gate/detector3/vis/forceWireframe
#/gate/detector3/vis/setVisible 0

# C R Y S T A L

/gate/detector3/daughters/name crystal3
/gate/detector3/daughters/insert box
/gate/crystal3/placement/setTranslation 0 0 0 cm
/gate/crystal3/geometry/setXLength 19   mm
/gate/crystal3/geometry/setYLength 7   mm
/gate/crystal3/geometry/setZLength 50    cm
/gate/crystal3/setMaterial EJ230
#/gate/crystal3/vis/forceSolid
#/gate/crystal3/vis/setColor white
#/gate/crystal3/vis/setVisible 1


# R E P E A T E R S

/gate/detector3/repeaters/insert ring
/gate/detector3/ring/setFirstAngle 1.9565217391304348 deg
/gate/detector3/ring/setRepeatNumber 96

# A T T A C H M E N T S

/gate/systems/detector3/level1/attach crystal3  
#/gate/crystal3/attachCrystalSD

